### ISSUE TITLE
Print error with WMTS layers

### ISSUE THREAD

**Issue by jusabatier** [sigrennesmetropole/geor_urbanisme_mapstore#70]
I installed the 2.1.1 version of the plugin and have errors printing.

When trying to print with a WMTS background : 

> geOrchestra.js?be9117ff58373242e31a:2 Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
>     at 934.a9ed89a1.js:1:239937
>     at Object.map (934.a9ed89a1.js:1:240250)
>     at 934.a9ed89a1.js:1:234410
>     at Array.map (<anonymous>)
>     at ci (934.a9ed89a1.js:1:234360)
>     at pu (934.a9ed89a1.js:1:297691)
>     at 934.a9ed89a1.js:1:326549
>     at geOrchestra.js?be9117ff58373242e31a:2:4507600
>     at geOrchestra.js?be9117ff58373242e31a:2:4514069
>     at onClick (934.a9ed89a1.js:1:145361)
>     at onClick (934.a9ed89a1.js:1:129961)
>     at Object.m (geOrchestra.js?be9117ff58373242e31a:2:3674865)
>     at w (geOrchestra.js?be9117ff58373242e31a:2:3675008)
>     at geOrchestra.js?be9117ff58373242e31a:2:3675154
>     at C (geOrchestra.js?be9117ff58373242e31a:2:3675240)
>     at k (geOrchestra.js?be9117ff58373242e31a:2:3675689)

**Comment by jusabatier** [comment]
@catmorales Can you reproduce this bug ?

If not is it possible for you to share me an export on your map so I can compare why our WMTS layer doesn't work ?

**Comment by jusabatier** [comment]
Ok, I tried to change the Mapstore2 submodule version to match the current one used by mapstore2-georchestra 2023.02.xx : 

```
cd Mapstore2
git checkout 1dfbf08442bbe7445c35cda9f6da7aa1083e4cbd
cd ..
npm install --legacy-peer-deps
NODE_OPTIONS=--openssl-legacy-provider npm run ext:build
```

Then the rebuild extension works well.
